name: Tester

on: push

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    environment: hdf

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Run PyTest
        run: |
          pip install pytest
          pytest
      
      - name: Print Statement
        run: python3 main.py

